### ISSUE TITLE
State doesn't refresh after calling server action from non-form element

### ISSUE THREAD

**Issue by NightClover-code** [NightClover-code/mini-reddit#1]
In the `user-profile.tsx` component, we call a `signOut` server action on a non-form element using an `onClick` handler.

After the users clicks on "Log out", the state doesn't refresh and the user can still see their profile avatar.

Only after refreshing or tabbing out of the screen can the user see the "Sign In With GitHub" button appear again.

The intended functionality is to update the state immediately after loggin out, and showing the login button again.

**Comment by vishnu-31** [comment]
I came across a similar issue of calling a *server action* using `onClick`.

You can try adding a form tag around it and using the `formAction` attribute of the button to call the server action.

**Comment by NightClover-code** [comment]
@vishnu-31 Thanks for the suggestion, but I already tried that.

The component used here is not really a button, it's the `DropDownItem` from Next UI, and it doesn't have a `type="submit"` for it to handle form submission.

`   
        <DropdownItem key="logout" color="danger" onClick={handleSignOut}>
          Log Out
        </DropdownItem>
`

**Comment by NightClover-code** [comment]
Close with solution from commit: [8dd58ca](https://github.com/NightClover-code/mini-reddit/commit/8dd58caaf7675f8b6c8045113ee93f6ddd71b586)
